#!/system/xbin/bash
#Bersihkan Layar
echo ""
echo ""
echo ""
echo ""
echo ""
pkg install figlet
clear
sleep 2
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat
figlet "MUKA LU KEK KONTOL"|lolcat

